# Configuration de Fly.io

app = "my-app"  # Nom de ton application Fly.io

kill_signal = "SIGINT"  # Le signal pour arrêter l'application
kill_timeout = 5  # Temps pour arrêter l'application

[build]
  # Si tu utilises Dockerfile, indique son emplacement
  dockerfile = "./Dockerfile"

[env]
  # Variables d'environnement, si nécessaire (ajoute des secrets par exemple)
  NODE_ENV = "production"

[[services]]
  http_checks = []  # Vérification HTTP (laisser vide si non nécessaire)
  internal_port = 3000  # Le port interne sur lequel ton application écoute
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25  # Limite maximale des connexions simultanées
    soft_limit = 20  # Limite douce pour les connexions
    type = "connections"

  [[services.ports]]
    handlers = ["http"]  # Gestion des ports HTTP
    port = 80  # Port externe
